### ISSUE TITLE
Can not recognize form fields

### ISSUE THREAD

**Issue by Chun-Yang** [johntayl/pdffiller#10]
I tried to get field names for thie file: http://www.irs.gov/pub/irs-pdf/f1040nr.pdf
```
pdfFiller.generateFDFTemplate(f1040nr, function (error, fdfData) {
  console.log(fdfData)
})
```
The result is always empty object.

**Comment by whitef0x0** [comment]
Sorry for the wait. 

I've fixed this issue (which has been tested) in Pull Request #14. 

If you are impatient and don't want to wait until this PR is merged, you can always use my fork (github.com/whitef0x0/pdffiller)[github.com/whitef0x0/pdffiller] until the changes are merged.

**Comment by whitef0x0** [comment]
This should be closed. Testing are passing and error reported is fixed
