### ISSUE TITLE
Multiple calls fdf.data conflict

### ISSUE THREAD

**Issue by dhautot** [johntayl/pdffiller#2]
Hi ! 

Great tool ! thanks!

When looping to generate several PDFs, a conflict seems to appear with the tempFDF = "data.fdf".

I solved this issue by changing the FDF name file in the index.js file : 

 var formData = fdf.generate( fieldValues ),
 tempFDF = "data" + (new Date().getTime()) + ".fdf";

This ensure that the tempFDF file will be unique at any time.

**Comment by harigopalakrishna** [comment]
I just created a pull request 18, to address this situation for high traffic pdf filling needs

**Comment by whitef0x0** [comment]
This is already fixed if you look at the current source code.

**Comment by whitef0x0** [comment]
@johntayl this issue should be closed. I fixed this a while ago and its confusing to new contributors to have solved issues still open.
