### ISSUE TITLE
Uppercase MD5 is now deprecated. FDF module should reference lowercase md5

### ISSUE THREAD

**Issue by ryates8** [johntayl/pdffiller#21]
https://www.npmjs.com/package/MD5

The index.js file within the fdf module references the deprecated version of md5. Not a big issue, but wanted to put it on your radar. We don't commit our node_modules so we had to request that everyone on the team fix this in their local copy's.

**Comment by whitef0x0** [comment]
I'll look into this tommorow.

**Comment by johntayl** [comment]
It looks like the FDF module requires, but never uses MD5. [See Here](https://github.com/countable/js-fdf/blob/master/index.coffee#L41)

**Comment by whitef0x0** [comment]
Maybe we should just move the XFDF instead? (see my most recent issue)

**Comment by johntayl** [comment]
Closing. See #22
