### ISSUE TITLE
Executing on Heroku

### ISSUE THREAD

**Issue by infos** [johntayl/pdffiller#25]
Hello - Your git is a major time saver from using iText. I am using it to fill PDF forms with data from a document in mongo db. However, I am running into issues when I deploy this to Heroku.

I am able to execute this hardcoded command and create the filled pdf on heroku bash. 
'pdftk in.pdf fill_form data145.fdf output filledout.pdf flatten'

But it does not work within my node api. I get a 'Process exited with status 143'. 

I wanted to see if you were able to deploy your app to heroku and create pdfs.

Thanks a bunch

**Comment by whitef0x0** [comment]
Does it work locally for you?

**Comment by infos** [comment]
I should have closed this. This works in heroku for us now. One of my developers fixed it. The PATH variable was incorrectly set.

**Comment by aphavichitr** [comment]
@infos how did you get this to run on heroku? I've added this buildpack to heroku: https://github.com/shake-apps/heroku-buildpack-pdftk and I'm not getting any errors when running pdfFiller.fillForm, however no file gets created after invoking that method. This works perfectly on my local machine, so there must be something that I missed.
