### ISSUE TITLE
Tests Fail?

### ISSUE THREAD

**Issue by deltreey** [johntayl/pdffiller#27]
I cloned the library and installed PDFtk for windows to try it out.  It passed all tests but one (btw, you should probably list mocha as a dev dependency and update the package,json `npm test` script).  The test was:

```javascript
it('should generate another FDF Template with no errors', function(done){
    this.timeout(15000);
    pdfFiller.generateFDFTemplate( source1PDF, null, function(err, fdfTemplate) { 
        should.not.exist(err);
        fdfTemplate.should.not.eql(expected.test1.fdfTemplate);
        done();
    });
});
```

Notice the should.**not**.eql  I'm confused.  This test failed because the output matched the expected data.  Maybe I'm missing something, but why shouldn't it?

**Comment by whitef0x0** [comment]
Yep you are right the test should say should.eql

**Comment by whitef0x0** [comment]
@johntayl can you close this?
