### ISSUE TITLE
npm install fails on Windows 10

### ISSUE THREAD

**Issue by deltreey** [johntayl/pdffiller#28]
I don't know why, but it appears to be complaining about an incompatible version of MD5 and talks about my system's architecture.

```bash
> npm install pdffiller --save
npm WARN deprecated MD5@1.3.0: deprecated, use lowercase 'md5@2.x' from now on
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\<username>\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "pdffiller" "--save"
npm ERR! node v5.1.1
npm ERR! npm  v3.5.1

npm ERR! No compatible version found: md5@~2.0.0
npm ERR! Valid install targets:
npm ERR! 1.3.0, 1.2.2, 1.2.1, 1.2.0, 1.1.0, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 0.0.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     <directory>\npm-debug.log
```

Any ideas?

**Comment by whitef0x0** [comment]
md5 error can be ignored

**Comment by whitef0x0** [comment]
hmmmm @deltreey did you get it to work?

**Comment by deltreey** [comment]
I'll take a look Monday probably.  My laptop is in pieces at the moment as I'm moving hard drives around.

**Comment by deltreey** [comment]
debug log attached.  Ran it on my Win 7 work PC.  See the debug log if you like.

https://gist.github.com/deltreey/34b3417484940fb7031f4b38245f1078

**Comment by whitef0x0** [comment]
@deltreey see this for a possible solution https://github.com/nodejs/node-v0.x-archive/issues/4047

**Comment by deltreey** [comment]
I am not encountering the issue currently.  I see it in a dependency list for an app that I work on regularly, and I don't remember what was wrong back when I posted this.  I'm closing this.
