### ISSUE TITLE
Licensing ambiguity

### ISSUE THREAD

**Issue by whitef0x0** [johntayl/pdffiller#4]
Hey there!

I'm currently working on a fork of pdffiller and I'm confused as to which license the project is using as you include the MIT license in your license.md file, however in your package.json file, the license is listed as BSD.

And if you are using BSD, could you please specify which version of BSD you are using (I'm assuming you are using the BSD-2/3 clause version)?

Cheers

**Comment by johntayl** [comment]
Good catch. This was overlooked when the license was updated. I'm using the MIT license.

Thanks!
