### ISSUE TITLE
Would it be possible to use utf8 characters?

### ISSUE THREAD

**Issue by lvarayut** [johntayl/pdffiller#5]
First of all, thanks for the great library. I generated a form filled with English words, it worked like a charm However, when I tried to fill with French or any other languages, I got some weir characters like `à1•à ̧€à ̧aà ̧±à ̧à ̧ ̈à ̧2à`. Is there any work around to come across this problem?

**Comment by whitef0x0** [comment]
Can you provide an example of input characters and their corresponding outputs?

**Comment by ExperimentalRat** [comment]
I am sending .fdf  data like this:
data = 
  'last_name' : 'Johnамва' (with 4 russian letters)
 and in PDF I got this:
  'last_name' : 'John'
Pls help me solve this problem, I've read if I will send .xfrf data it could help but also I dont know how to set in PDF required fields, I mean I tried to send data to empty PDF and nothing changes, so I need to prepare PDF somehow, but how?Thx.

**Comment by whitef0x0** [comment]
Seem like this is due to lack of utf8 support in one of our dependencies, https://github.com/countable/js-fdf

**Comment by whitef0x0** [comment]
This has been fixed. See PR#30

**Comment by whitef0x0** [comment]
@johntayl this should be closed
