### ISSUE TITLE
Update/republish NPM package

### ISSUE THREAD

**Issue by whitef0x0** [johntayl/pdffiller#8]
Npm package is still at old release.

**Comment by johntayl** [comment]
Didn't know it was on NPM, someone else has published the repo. I don't have access to update it.

**Comment by Chun-Yang** [comment]
Can you rename this package? Or create a new repo and fork this then rename it?

**Comment by johntayl** [comment]
Updated NPM package is now available. [node-pdffiller](https://www.npmjs.com/package/node-pdffiller)
